from bot.handlers.private_chat import register_private_chat_handlers
from bot.handlers.general_chat import register_general_chat_handlers
from bot.handlers.temp_handler import register_temp_chat_handlers